<script src="{{ asset('jquery/js/jquery-3.2.1.js')}}"></script>
<script src="{{ asset('js/siie.js')}}"></script>
<script src="{{ asset('chosen/chosen.jquery.js') }}"></script>
<script src="{{ asset('js/chosen-selects.js')}}"></script>
<script src="{{ asset('bootstrap/js/bootstrap.min.js')}}"></script>
<script src="{{ asset('trumbowyg/dist/trumbowyg.min.js') }}"></script>
<script src="{{ asset('vue/vue.min.js') }}"></script>
<script src="{{ asset('datatables/datatables.min.js') }}"></script>
<script src="{{ asset('sweet-alert/sweetalert2.min.js') }}"></script>
<script src="{{ asset('datatables/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('datatables/buttons.flash.min.js') }}"></script>
<script src="{{ asset('datatables/jszip.min.js') }}"></script>
<script src="{{ asset('datatables/pdfmake.min.js') }}"></script>
<script src="{{ asset('datatables/vfs_fonts.js') }}"></script>
<script src="{{ asset('datatables/buttons.html5.min.js') }}"></script>
<script src="{{ asset('datatables/buttons.print.min.js') }}"></script>
