<script src="{{ asset('jquery/js/jquery-3.2.1.js')}}"></script>
<script src="{{ asset('js/siie.js')}}"></script>
<script src="{{ asset('chosen/chosen.jquery.js') }}"></script>
<script src="{{ asset('js/chosen-selects.js')}}"></script>
<script src="{{ asset('vue/vue.min.js') }}"></script>
<script src="{{ asset('bootstrap/js/bootstrap.min.js')}}"></script>
<script src="{{ asset('trumbowyg/dist/trumbowyg.min.js') }}"></script>
<script src="{{ asset('datatables/datatables.min.js') }}"></script>
<script src="{{ asset('js/wms/stocktable.js')}}"></script>
<script src="{{ asset('sweet-alert/sweetalert2.min.js') }}"></script>
<script src="{{ asset('js/wms/stock/SKardex.js') }}"></script>
<script src="{{ asset('js/wms/stock/SGuiKardex.js') }}"></script>
