<script src="{{ asset('jquery/js/jquery-3.2.1.js')}}"></script>
<script src="{{ asset('js/siie.js')}}"></script>
<script src="{{ asset('chosen/chosen.jquery.js') }}"></script>
<script src="{{ asset('js/chosen-selects.js')}}"></script>
<script src="{{ asset('bootstrap/js/bootstrap.min.js')}}"></script>
<script src="{{ asset('vue/vue.min.js') }}"></script>
<script src="{{ asset('datatables/datatables.min.js') }}"></script>
{{-- https://sweetalert.js.org/ --}}
{{-- <script src="{{ asset('sweet-alert/sweetalert.min.js') }}"></script> --}}
<script src="{{ asset('sweet-alert/sweetalert2.min.js') }}"></script>
<script src="{{ asset('js/movements/SGuiFunctions.js')}}"></script>
<script src="{{ asset('js/movements/SGuiValidations.js')}}"></script>
<script src="{{ asset('js/movements/SHeaderCore.js')}}"></script>
<script src="{{ asset('js/movements/Movements.js')}}"></script>
{{-- <script src="{{ asset('js/movements/movementrows.js')}}"></script> --}}
{{-- <script src="{{ asset('js/movements/lotrows.js')}}"></script> --}}
{{-- <script src="{{ asset('js/movements/pallets.js')}}"></script> --}}
{{-- <script src="{{ asset('js/movements/validations.js')}}"></script> --}}
{{-- <script src="{{ asset('js/movements/progressbar.js')}}"></script> --}}
<script src="{{ asset('js/movements/SContainersValidation.js')}}"></script>
<script src="{{ asset('js/movements/SPalletCore.js')}}"></script>
<script src="{{ asset('js/movements/SItemSelection.js')}}"></script>
<script src="{{ asset('js/movements/SRowsCore.js')}}"></script>
<script src="{{ asset('js/movements/SLotsCore.js')}}"></script>
<script src="{{ asset('js/movements/SStockCore.js')}}"></script>
<script src="{{ asset('js/movements/SGuiTransSupp.js')}}"></script>
<script src="{{ asset('js/movements/SSupplyCore.js')}}"></script>
<script src="{{ asset('js/movements/tables.js')}}"></script>
<script src="{{ asset('js/items/table.js')}}"></script>
<script src="{{ asset('js/movements/lots_table.js')}}"></script>
<script src="{{ asset('js/movements/stock_table.js')}}"></script>
<script src="{{ asset('js/movements/validations.js')}}"></script>
<script src="{{ asset('progressbar/bootstrap-progressbar.min.js')}}"></script>
