<script src="{{ asset('jquery/js/jquery-3.2.1.js')}}"></script>
<script src="{{ asset('js/siie.js')}}"></script>
<script src="{{ asset('chosen/chosen.jquery.js') }}"></script>
<script src="{{ asset('js/chosen-selects.js')}}"></script>
<script src="{{ asset('bootstrap/js/bootstrap.min.js')}}"></script>
<script src="{{ asset('trumbowyg/dist/trumbowyg.min.js') }}"></script>
<script src="{{ asset('vue/vue.min.js') }}"></script>
{{-- <script src="{{ asset('datatables/datatables.min.js') }}"></script> --}}
<script src="{{ asset('js/movements/Movements.js')}}"></script>
<script src="{{ asset('js/movements/movementrows.js')}}"></script>
<script src="{{ asset('js/movements/lotrows.js')}}"></script>
{{-- <script src="{{ asset('js/movements/tables.js')}}"></script> --}}
<script src="{{ asset('js/movements/validations.js')}}"></script>
{{-- <script src="{{ asset('tabletojson/jquery.tabletojson.min.js')}}"></script> --}}
